documentation:
  image: julia:1.8.5
  stage: deploy
  script:
    - |
      julia --project=docs -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()
        using Documenter: doctest
        using .jdiva
        doctest(jdiva)
        include("docs/make.jl")'
    - mkdir -p public
    - mv docs/build/* public/
  artifacts:
    paths:
      - public
  only:
    - development