pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r documentation/* .public
    - rm -rf .public/templates/docs
    - mkdir .public/templates/docs
    - cp -r docs/build/* .public/templates/docs
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - development