pages:
  script:
    - apt-get update -qq && apt-get install -y git # needed by Documenter
    - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("GitlabJuliaDemo");' # rebuild Julia
    - julia -e 'using Pkg; import GitlabJuliaDemo; Pkg.add("Documenter")' # install Documenter
    - julia --color=yes docs/make.jl # make documentation
    - mkdir .public
    - cp -r docs/build/* .public
    - mv .public public
    
  artifacts:
    paths:
      - public
  only:
    - development


 