import Pkg

Pkg.add("GeoFormatTypes")
Pkg.add("GDAL")
Pkg.add("CoordinateTransformations")
Pkg.add("StaticArrays")
Pkg.add("StructArrays")
Pkg.add("NCDatasets")
Pkg.add("DataStructures")
Pkg.add("QuadGK")
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("Documenter")
Pkg.add("Distributions")
Pkg.add("Plots")
Pkg.add("NearestNeighbors")
Pkg.add("Distances")
Pkg.add("LsqFit")
Pkg.add("ThreadPools")
Pkg.add("LsqFit")
Pkg.add("NearestNeighbors")
Pkg.add("Distances")
Pkg.add("IterTools")
Pkg.add("Optim")
Pkg.add("ThreadPools")